In [106]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [107]:
df=pd.read_csv('Raw Property.csv')

In [108]:
df

,Property_Name,Location,Price,Built-up Area,Bedroom,Property_Age,Furnish
0,Kalpataru Radiance,Goregaon West,3.3 Cr,1200 sq.ft,2 BHK Flat,NaN,Semi Furnished
1,Monte Verita North Annexe Phase 1,Borivali East,1.4 Cr,652 sq.ft,2 BHK Flat,1 Years Old,Unfurnished
2,Sheth VASANTOASIS BLOSSOM BLDG 20 WING A AND W...,khopte,3.35 Cr,1240 sq.ft,3 BHK Flat,1 Years Old,Unfurnished
3,DLH The Park Residences Phase 1,Andheri West,5.35 Cr,1300 sq.ft,3 BHK Flat,3 Year Old,Semi Furnished
4,Oberoi Eternia Towers A to D,Mulund West,3.0 Cr,1350 sq.ft,3 BHK Flat,1 Years Old,Semi Furnished
...,...,...,...,...,...,...,...
14995,NaN,Mulund West,1.31 Cr,565 sq.ft,2 BH Flat,NaN,Fully Furnished
14996,NaN,Santacruz East,2.3 Cr,956 sq.ft,2 BHK Flat,5 Year Old,Unfurnished
14997,NaN,Mira Road West,55.0 L,531 sq.ft,1 BHK Independent House,5 Year Old,Unfurnished
14998,NaN,Borivali West,1.2 Cr,550 sq.ft,1 BHK Flat,15 Year Old,Fully Furnished
14999,NaN,Vile Parle East,1.75 Cr,445 sq.ft,1 BHK Flat,6 Year Old,Semi Furnished

In [109]:
print(df.columns)

Index(['Property_Name', 'Location', 'Price', 'Built-up Area', 'Bedroom',
       'Property_Age', 'Furnish'],
      dtype='object')

In [110]:
nan_counts = df.isna().sum()
nan_counts

Property_Name    5060
Location           31
Price              31
Built-up Area      31
Bedroom            31
Property_Age     2028
Furnish            72
dtype: int64

In [111]:
df=df.dropna(how='all')
df.reset_index(drop=True, inplace=True)
df

,Property_Name,Location,Price,Built-up Area,Bedroom,Property_Age,Furnish
0,Kalpataru Radiance,Goregaon West,3.3 Cr,1200 sq.ft,2 BHK Flat,NaN,Semi Furnished
1,Monte Verita North Annexe Phase 1,Borivali East,1.4 Cr,652 sq.ft,2 BHK Flat,1 Years Old,Unfurnished
2,Sheth VASANTOASIS BLOSSOM BLDG 20 WING A AND W...,khopte,3.35 Cr,1240 sq.ft,3 BHK Flat,1 Years Old,Unfurnished
3,DLH The Park Residences Phase 1,Andheri West,5.35 Cr,1300 sq.ft,3 BHK Flat,3 Year Old,Semi Furnished
4,Oberoi Eternia Towers A to D,Mulund West,3.0 Cr,1350 sq.ft,3 BHK Flat,1 Years Old,Semi Furnished
...,...,...,...,...,...,...,...
14964,NaN,Mulund West,1.31 Cr,565 sq.ft,2 BH Flat,NaN,Fully Furnished
14965,NaN,Santacruz East,2.3 Cr,956 sq.ft,2 BHK Flat,5 Year Old,Unfurnished
14966,NaN,Mira Road West,55.0 L,531 sq.ft,1 BHK Independent House,5 Year Old,Unfurnished
14967,NaN,Borivali West,1.2 Cr,550 sq.ft,1 BHK Flat,15 Year Old,Fully Furnished
14968,NaN,Vile Parle East,1.75 Cr,445 sq.ft,1 BHK Flat,6 Year Old,Semi Furnished

In [112]:
nan_counts = df.isna().sum()
nan_counts

Property_Name    5029
Location            0
Price               0
Built-up Area       0
Bedroom             0
Property_Age     1997
Furnish            41
dtype: int64

In [113]:
df['Built-up Area'] = df['Built-up Area'].str.split(' ').str[0].astype(int)
df['Bedroom'] = df['Bedroom'].str.split(' ').str[0].astype(float)
df['Price Unit'] = df['Price'].str.split(' ').str[1]
for i in range (0,len(df)):
    if df['Price Unit'][i] == 'Cr':
        df['Price'][i] = float(df['Price'][i].split(' ')[0]) * 10000000
    elif df['Price Unit'][i] == 'L' or df['Price Unit'][i] == 'Lacs' or df['Price Unit'][i] == 'Lac' or df['Price Unit'][i] == 'L(negotiable)':
        df['Price'][i] = float(df['Price'][i].split(' ')[0]) * 100000
    else:
      df['Price'][i] = float(df['Price'][i].replace(',',''))
df['Property_Age'] = df['Property_Age'].dropna().apply(lambda x: float(x.split()[0]))
df['Property_Age'].fillna(df['Property_Age'].median(), inplace=True)
df['Property_Name'] = df['Property_Name'].fillna('Unnamed Property')
df['Furnish'] = df['Furnish'].fillna('Unfurnished')
df

,Property_Name,Location,Price,Built-up Area,Bedroom,Property_Age,Furnish,Price Unit
0,Kalpataru Radiance,Goregaon West,33000000.0,1200,2.0,6.0,Semi Furnished,Cr
1,Monte Verita North Annexe Phase 1,Borivali East,14000000.0,652,2.0,1.0,Unfurnished,Cr
2,Sheth VASANTOASIS BLOSSOM BLDG 20 WING A AND W...,khopte,33500000.0,1240,3.0,1.0,Unfurnished,Cr
3,DLH The Park Residences Phase 1,Andheri West,53500000.0,1300,3.0,3.0,Semi Furnished,Cr
4,Oberoi Eternia Towers A to D,Mulund West,30000000.0,1350,3.0,1.0,Semi Furnished,Cr
...,...,...,...,...,...,...,...,...
14964,Unnamed Property,Mulund West,13100000.0,565,2.0,6.0,Fully Furnished,Cr
14965,Unnamed Property,Santacruz East,23000000.0,956,2.0,5.0,Unfurnished,Cr
14966,Unnamed Property,Mira Road West,5500000.0,531,1.0,5.0,Unfurnished,L
14967,Unnamed Property,Borivali West,12000000.0,550,1.0,15.0,Fully Furnished,Cr
14968,Unnamed Property,Vile Parle East,17500000.0,445,1.0,6.0,Semi Furnished,Cr

In [114]:
df.isna().sum()

Property_Name    0
Location         0
Price            0
Built-up Area    0
Bedroom          0
Property_Age     0
Furnish          0
Price Unit       3
dtype: int64

In [115]:
df.duplicated().sum()

745

In [116]:
df = df.drop_duplicates(ignore_index=True)
df

,Property_Name,Location,Price,Built-up Area,Bedroom,Property_Age,Furnish,Price Unit
0,Kalpataru Radiance,Goregaon West,33000000.0,1200,2.0,6.0,Semi Furnished,Cr
1,Monte Verita North Annexe Phase 1,Borivali East,14000000.0,652,2.0,1.0,Unfurnished,Cr
2,Sheth VASANTOASIS BLOSSOM BLDG 20 WING A AND W...,khopte,33500000.0,1240,3.0,1.0,Unfurnished,Cr
3,DLH The Park Residences Phase 1,Andheri West,53500000.0,1300,3.0,3.0,Semi Furnished,Cr
4,Oberoi Eternia Towers A to D,Mulund West,30000000.0,1350,3.0,1.0,Semi Furnished,Cr
...,...,...,...,...,...,...,...,...
14219,Unnamed Property,Mulund West,13100000.0,565,2.0,6.0,Fully Furnished,Cr
14220,Unnamed Property,Santacruz East,23000000.0,956,2.0,5.0,Unfurnished,Cr
14221,Unnamed Property,Mira Road West,5500000.0,531,1.0,5.0,Unfurnished,L
14222,Unnamed Property,Borivali West,12000000.0,550,1.0,15.0,Fully Furnished,Cr
14223,Unnamed Property,Vile Parle East,17500000.0,445,1.0,6.0,Semi Furnished,Cr

In [117]:
print('Shape of Data :', df.shape)
df

Shape of Data : (14224, 8)

,Property_Name,Location,Price,Built-up Area,Bedroom,Property_Age,Furnish,Price Unit
0,Kalpataru Radiance,Goregaon West,33000000.0,1200,2.0,6.0,Semi Furnished,Cr
1,Monte Verita North Annexe Phase 1,Borivali East,14000000.0,652,2.0,1.0,Unfurnished,Cr
2,Sheth VASANTOASIS BLOSSOM BLDG 20 WING A AND W...,khopte,33500000.0,1240,3.0,1.0,Unfurnished,Cr
3,DLH The Park Residences Phase 1,Andheri West,53500000.0,1300,3.0,3.0,Semi Furnished,Cr
4,Oberoi Eternia Towers A to D,Mulund West,30000000.0,1350,3.0,1.0,Semi Furnished,Cr
...,...,...,...,...,...,...,...,...
14219,Unnamed Property,Mulund West,13100000.0,565,2.0,6.0,Fully Furnished,Cr
14220,Unnamed Property,Santacruz East,23000000.0,956,2.0,5.0,Unfurnished,Cr
14221,Unnamed Property,Mira Road West,5500000.0,531,1.0,5.0,Unfurnished,L
14222,Unnamed Property,Borivali West,12000000.0,550,1.0,15.0,Fully Furnished,Cr
14223,Unnamed Property,Vile Parle East,17500000.0,445,1.0,6.0,Semi Furnished,Cr

In [121]:
df.to_csv('Property.csv', index=False)