In [ ]:
import timeit
import pandas as pd
from requests import get
from bs4 import BeautifulSoup

import warnings
warnings.filterwarnings('ignore')

In [ ]:
start = 1
stop  = 101

# headers = {'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.11 (KHTML, like Gecko) Chrome/23.0.1271.64 Safari/537.11',
#            'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
#            'Accept-Charset': 'ISO-8859-1,utf-8;q=0.7,*;q=0.3',
#            'Accept-Encoding': 'none',
#            'Accept-Language': 'en-US,en;q=0.8',
#            'Connection': 'keep-alive'}

In [ ]:
def property_nane(soupy_object):   # return house or property name
    try:
        name = soupy_object.find('a', attrs = {'class':'_h3i2wt T_46c25558 _rd8stv T_28a1665a _ks15vq _vv1q9c _sq1l2s T_091c165f'}).text
    except:
        name = None
    return name

def address_details(soupy_object):   # return address of property
    try:
        address = soupy_object.find('div', attrs = {'data-q':'address'}).text.split(',')[-2]
    except:
        address = None
    return address

def total_price(soupy_object):   # return total price of property
    try:
        price = soupy_object.find_all('div', attrs={'class': '_h3i2wt T_46c25558'})[1].text
    except:
        price = None
    return price

def rate_sqft(soupy_object):   # return total price of property
    try:
        rate = soupy_object.find('div', attrs = {'class':"css-1k19e3"}).text
    except:
        rate = None
    return rate

# def area_type(soupy_object):   # return area parameters
#     try:
#         areatyp = soupy_object.find('div', attrs = {'id':'factArea'}).text
#     except:
#         areatyp = None
#     return areatyp



def bedroom_count(soupy_object):   # return number of bedrooms
    try:
        bedroom = soupy_object.find('div', attrs={"class":"css-1hidc9c"}).text
    except:
        bedroom = None
    return bedroom

# def bathroom_count(soupy_object):   # return number of bathrooms
#     try:
#         bathroom =  soupy_object.find('span', attrs= {'id':'bathroomNum'}).text.split(' ')[0]
#     except:
#         bathroom = None
#     return bathroom

# def floor_num(soupy_object):   # return number of floor
#     try:
#         floornum = soupy_object.find('span', attrs = {'id':'floorNumLabel'}).text.split(' ')[0]
#     except:
#         floornum = None
#     return floornum

def property_age(soupy_object):   # return age of property
    age = None
    try:
        divs = soupy_object.find_all('div', attrs={"class":"css-1k19e3"})
        for div in divs:
            if (('old' in div.text.lower()) or ('year' in div.text.lower())):  # Case-insensitive match
                age = div.text
    except:
        age = None
    return age

def availability(soupy_object):   # return area parameters
    avail = None
    try:
        divs = soupy_object.find_all('div', attrs={"class":"css-1k19e3"})
        for div in divs:
            if 'furnished' in div.text.lower():  # Case-insensitive match
                avail = div.text
    except:
        avail = None
    return avail

In [ ]:
data_list = []
def get_all(start, stop):
    for pagenumber in range(start, stop):
        timestart = timeit.default_timer()
        url = f'https://housing.com/in/buy/searches/AB1AC0CePskwz0ocdh7q42r5?page={pagenumber}'
        req = get(url)
        soup = BeautifulSoup(req.content, 'html.parser')
        links = soup.find_all('a', attrs= {"data-q":"title"})

        for k, item in enumerate(links):
            main_url = 'https://www.housing.com'
            sub_url = item.get('href')
            data_url = main_url + sub_url
            request = get(data_url)
            soup_get = BeautifulSoup(request.content, 'html.parser')

            name = property_nane(soup_get)
            address = address_details(soup_get)
            price = total_price(soup_get)
            rate = rate_sqft(soup_get)
            # areatyp = area_type(soup_get)
            bedroom = bedroom_count(soup_get)
            # bathroom = bathroom_count(soup_get)
            # floornum = floor_num(soup_get)
            age = property_age(soup_get)
            avail = availability(soup_get)

            data = {'Property_Name': name, 'Location': address,
                    'Price':price, 'Built-up Area':rate, #'Area_Tpye':areatyp,
                    'Bedroom': bedroom,
                    # 'Bathroom':bathroom, 'Floor_No':floornum,
                    'Property_Age':age,
                    'Furnish':avail
                    }
            data_list.append(data)


        timestop = timeit.default_timer()
        print(f'You scraped page no : {pagenumber}')
        print('Time :', timestop - timestart)

    return data_list

In [ ]:
df1 = pd.DataFrame(get_all(start, stop))

You scraped page no : 1
Time : 47.63271922299998
You scraped page no : 2
Time : 53.30232637500001
You scraped page no : 3
Time : 56.197403286999986
You scraped page no : 4
Time : 57.21648371700002
You scraped page no : 5
Time : 55.915602723000006
You scraped page no : 6
Time : 57.537289343
You scraped page no : 7
Time : 55.88966089200005
You scraped page no : 8
Time : 57.195671925000056
You scraped page no : 9
Time : 56.59731316399996
You scraped page no : 10
Time : 58.00925990600001
You scraped page no : 11
Time : 57.30268033700008
You scraped page no : 12
Time : 55.05931579000003
You scraped page no : 13
Time : 54.83632407500011
You scraped page no : 14
Time : 54.98751186599998
You scraped page no : 15
Time : 56.59868473099982
You scraped page no : 16
Time : 55.641597722999904
You scraped page no : 17
Time : 54.95295514899999
You scraped page no : 18
Time : 56.43476022200002
You scraped page no : 19
Time : 50.665250231999835
You scraped page no : 20
Time : 56.38337100900003
You scraped page no : 21
Time : 55.05053980399998
You scraped page no : 22
Time : 55.102255472000024
You scraped page no : 23
Time : 56.073816879000105
You scraped page no : 24
Time : 56.30768741599991
You scraped page no : 25
Time : 56.186171953999974
You scraped page no : 26
Time : 54.597743604000016
You scraped page no : 27
Time : 56.12938649099988
You scraped page no : 28
Time : 55.928932423000106
You scraped page no : 29
Time : 56.62594360600019
You scraped page no : 30
Time : 60.37867273699999
You scraped page no : 31
Time : 55.42062153300003
You scraped page no : 32
Time : 56.786382413999945
You scraped page no : 33
Time : 57.97410808399991
You scraped page no : 34
Time : 55.76880470800006
You scraped page no : 35
Time : 59.72189940299995
You scraped page no : 36
Time : 58.31747060299995
You scraped page no : 37
Time : 62.79030034800007
You scraped page no : 38
Time : 66.621744778
You scraped page no : 39
Time : 53.38447004700038
You scraped page no : 40
Time : 56.81809780599997
You scraped page no : 41
Time : 54.51456789599979
You scraped page no : 42
Time : 57.440984049000235
You scraped page no : 43
Time : 54.80247223300012
You scraped page no : 44
Time : 55.89242358799993
You scraped page no : 45
Time : 56.31903453699988
You scraped page no : 46
Time : 56.30726602899995
You scraped page no : 47
Time : 54.5085861739999
You scraped page no : 48
Time : 54.64594269999998
You scraped page no : 49
Time : 55.57413180899994
You scraped page no : 50
Time : 55.641989145000025
You scraped page no : 51
Time : 56.35872903599966
You scraped page no : 52
Time : 62.88095198699966
You scraped page no : 53
Time : 54.81618230699996
You scraped page no : 54
Time : 55.85619917899976
You scraped page no : 55
Time : 55.5111469819999
You scraped page no : 56
Time : 55.31836559800013
You scraped page no : 57
Time : 57.512781994000306
You scraped page no : 58
Time : 55.25800422700013
You scraped page no : 59
Time : 56.31840019099991
You scraped page no : 60
Time : 57.733941204000075
You scraped page no : 61
Time : 63.3442919160002
You scraped page no : 62
Time : 59.188258314999985
You scraped page no : 63
Time : 55.733210418
You scraped page no : 64
Time : 61.39179451000018
You scraped page no : 65
Time : 65.47511220500019
You scraped page no : 66
Time : 57.86031140499972
You scraped page no : 67
Time : 56.45407370300018
You scraped page no : 68
Time : 58.28833859400038
You scraped page no : 69
Time : 53.768263933000526
You scraped page no : 70
Time : 64.36044156499975
You scraped page no : 71
Time : 56.28206350900018
You scraped page no : 72
Time : 58.661044296
You scraped page no : 73
Time : 58.91511599500063
You scraped page no : 74
Time : 57.174819279000076
You scraped page no : 75
Time : 54.94121555499987
You scraped page no : 76
Time : 56.54274835999968
You scraped page no : 77
Time : 58.69974442399962
You scraped page no : 78
Time : 56.85440411400032
You scraped page no : 79
Time : 60.202685869999186
You scraped page no : 80
Time : 59.18393538500004
You scraped page no : 81
Time : 55.74471808499948
You scraped page no : 82
Time : 55.4833658309999
You scraped page no : 83
Time : 56.83650612499969
You scraped page no : 84
Time : 60.41135433499949
You scraped page no : 85
Time : 54.827389480999955
You scraped page no : 86
Time : 56.14348107099977
You scraped page no : 87
Time : 56.0881106450006
You scraped page no : 88
Time : 58.78327750199969
You scraped page no : 89
Time : 56.94425404999947
You scraped page no : 90
Time : 56.56563241099957
You scraped page no : 91
Time : 56.60899861599955
You scraped page no : 92
Time : 55.658976732000156
You scraped page no : 93
Time : 56.44083675300044
You scraped page no : 94
Time : 57.39798820099986
You scraped page no : 95
Time : 54.049119997999696
You scraped page no : 96
Time : 55.11676603900014
You scraped page no : 97
Time : 54.77495265900052
You scraped page no : 98
Time : 59.44204298400018
You scraped page no : 99
Time : 55.010751970000456
You scraped page no : 100
Time : 58.39826273000017

In [ ]:
df1

,Unnamed: 0,Property_Name,Location,Price,Built-up Area,Bedroom,Property_Age,Furnish
0,0,Kalpataru Radiance,Goregaon West,3.3 Cr,1200 sq.ft,2 BHK Flat,NaN,Semi Furnished
1,1,Monte Verita North Annexe Phase 1,Borivali East,1.4 Cr,652 sq.ft,2 BHK Flat,1 Years Old,Unfurnished
2,2,Sheth VASANTOASIS BLOSSOM BLDG 20 WING A AND W...,khopte,3.35 Cr,1240 sq.ft,3 BHK Flat,1 Years Old,Unfurnished
3,3,DLH The Park Residences Phase 1,Andheri West,5.35 Cr,1300 sq.ft,3 BHK Flat,3 Year Old,Semi Furnished
4,4,Oberoi Eternia Towers A to D,Mulund West,3.0 Cr,1350 sq.ft,3 BHK Flat,1 Years Old,Semi Furnished
...,...,...,...,...,...,...,...,...
2995,2995,Atul Blue Horizon,Goregaon West,1.74 Cr,850 sq.ft,2 BHK Flat,19 Year Old,Semi Furnished
2996,2996,Asmita Jyoti CHS,Malad West,82.0 L,540 sq.ft,1 BHK Flat,15 Year Old,Unfurnished
2997,2997,Tridhaatu Morya,Chembur,1.45 Cr,550 sq.ft,1 BHK Flat,NaN,Unfurnished
2998,2998,Sunteck West World 2 Tivri Naigaon East,Naigaon East,32.0 L,610 sq.ft,1 BHK Flat,1 Years Old,Unfurnished
2999,2999,Sunteck Maxx World,Naigaon East,34.5 L,620 sq.ft,1 BHK Flat,NaN,Unfurnished

In [ ]:
df1.to_csv('Prop_1_100.csv')